version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: exoplanet_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  nestjs:
    build: .
    container_name: exoplanet_nestjs
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/exoplanet

volumes:
  mongo_data:
